config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'welcome#index', as: :home

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  # get('/posts/new', { to: 'posts#new', as: :new_post })
  # post('/posts', { to: 'posts#create', as: :posts })
  # get('/posts/:id', { to: 'posts#show', as: :post })
  # get('/posts', { to: 'posts#index' })
  # get('/posts/:id/edit', { to: 'posts#edit', as: :edit_post })
  # patch('/posts/:id', { to: 'posts#update' })
  # delete('/posts/:id', { to: 'posts#destroy' })
  resources :users
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :nullify
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :category, optional: true
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :posts, dependent: :nullify
  has_many :comments, dependent: :nullify

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def user_signed_in?
    if session[:user_id].present? && current_user.nil?
      session[:user_id] = nil
    end
    
    session[:user_id].present?
  end

  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def authenticate_user!
    if !user_signed_in?
      redirect_to new_session_path, notice: 'Please sign in!'
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    i = params.require(:comment).permit([:body])
    @post = Post.find params[:post_id]
    @comment = Comment.new i
    @comment.post = @post
    @comment.user = current_user
    if @comment.save
      flash[:notice] = 'Comment created'
      redirect_to post_path(@post)
    else
      flash[:alert] = 'Comment failed'
      render 'posts/show'
    end
  end

  def destroy
    comment = Comment.find params[:id]
    # @post = Post.find params[:post_id]
    @post = comment.post
    comment.destroy
    flash[:alert] = 'comment deleted'
    redirect_to post_path(@post)
  end

  private

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
  end

  def create
    k = params.require(:post).permit([:title, :body])
    @post = Post.new k
    @post.user = current_user
    if @post.save
      flash[:notice] = 'new post created'
      redirect_to post_path(@post.id)

    else
      flash[:alert] = 'failed to create a post'
      render :new
    end
  end

  def show
    @post = Post.find params[:id]
    # @comment = @post.comments.new
    @comment = Comment.new
    @comments = @post.comments.order(created_at: :desc)
  end

  def index
    @posts = Post.all
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    k = params.require(:post).permit([:title, :body])
    @post = Post.find params[:id]
    @post.update k
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find params[:id]
    @post.destroy
    redirect_to posts_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    # byebug
    if @user.present? && @user.authenticate(params[:password])
      flash[:notice] = 'Login successful'
      session[:user_id] = @user.id
      redirect_to home_url
    else
    flash.now[:alert] = 'try again'
    render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to home_path, notice: 'Signed Out! 🏃'
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    u = params.require(:user).permit([:first_name, :last_name, :email, :password])
    @user = User.new u
    if @user.save
      redirect_to home_path
      flash[:notice] = 'new user created'
    else
      flash[:alert] = 'failed'
      render :new
    end

    def edit
      @user = User.find params[:id]
    end

    def update
      u = params.require(:user).permit([:first_name, :last_name, :email, :password])
      @user.update u
      redirect_to home_path
      flash[:notice] = 'User updated'
    end
    
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <div class="navbar navbar-fixed-top navbar-inverse">
      <ul>
        <%= link_to 'Home', home_path %>
        |
        <%= link_to 'Posts', posts_path %>
        |
        <% if user_signed_in? %>
          <%= link_to 'Sign out', sessions_path, method: :delete %>
          Hello<%= current_user.full_name %>
        <% else %>
          <%= link_to 'Sign in', new_session_path %>
          |
          <%= link_to 'Sign up', new_user_path %>
        <% end %>
      </ul>
    </div>
    <hr>

    <% if flash[:notice] %>
      <div class='alert alert-success'><%= flash[:notice] %></div>
    <% elsif flash[:alert] %>
      <div class='alert alert-danger'><%= flash[:alert] %></div>
    <% end %>

    <br>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit post page</h1>

<%= form_for @post do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit %>

<% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <%= link_to post.title, post_path(post) %>
  <hr>
<% end %>

app/views/posts/new.html.erb
<h1>New post page</h1>

<% if @post.errors.present? %>
  <%= @post.errors.full_messages.join(', ') %>
<% end %>

<%= form_for @post do |f| %>
<div class="">
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>

<div class="">
  <%= f.label :body %>
  <%= f.text_area :body %>
</div>

  <%= f.submit %>

<% end %>

app/views/posts/show.html.erb
<h1>Post page</h1>

<div class="form-group">
  <h3><%= @post.title %></h3>
  <p><%= @post.body %></p>
  <p><strong>Author: </strong><%= @post.user.full_name %></p>

</div>

<%= link_to 'Edit', edit_post_path(@post) %>
<%= link_to 'Delete', post_path(@post), method: :delete %>
<hr>

<h1>Comment</h1>

<% if @comment.errors.present? %>
  <%= @comment.errors.full_messages.join(', ') %>
<% end %>

<div class="form-group">
  <%= form_for ([@post, @comment]) do |f| %>
  <div class="">
    <%= f.text_area :body %>
  </div>
    <%= f.submit  %>
  <% end  %>
</div>


<% @comments&.each do |comment| %>
<div class="container">
  <div class="row">
    <%= comment.body %>
    <p><strong>Author: </strong><%= comment.user.full_name %></p>
    <%= link_to 'Delete', post_comment_path(@post,comment), method: :delete %>
  </div>
  <hr>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<% if @user.errors.present? %>
  <%= @user.errors.full_messages.join(', ') %>
<% end %>

<%= form_for @user do |f| %>
<%= f.label :first_name %>
<%= f.text_field :first_name %>

<%= f.label :last_name %>
<%= f.text_field :last_name %>

<%= f.label :email %>
<%= f.email_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>

<%= f.submit %>


<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for @user do |f| %>
<%= f.label :first_name %>
<%= f.text_field :first_name %>

<%= f.label :last_name %>
<%= f.text_field :last_name %>

<%= f.label :email %>
<%= f.email_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>

<%= f.submit %>


<% end %>

app/views/welcome/index.html.erb
<h1>BloGG</h1>

<%= link_to 'New post', new_post_path %>